import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { HttpClient, generate } from "openapi-typescript-codegen";

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const contractsDir = path.resolve(currentDir, "..");
const specPath = path.join(contractsDir, "openapi", "openapi.yaml");
const generatedPackageDir = path.join(contractsDir, "..", "generated-client");
const generatedSrcDir = path.join(generatedPackageDir, "src");
const generatedOutputDir = path.join(generatedSrcDir, "generated");

async function main() {
  await mkdir(generatedSrcDir, { recursive: true });
  await rm(generatedOutputDir, { recursive: true, force: true });

  await generate({
    input: specPath,
    output: generatedOutputDir,
    httpClient: HttpClient.FETCH,
    useUnionTypes: false,
    exportSchemas: true,
  });

  await writeFile(
    path.join(generatedSrcDir, "index.ts"),
    [
      "// This package exposes the generated OpenAPI client for web and mobile consumers.",
      "// Do not edit files under src/generated by hand. Regenerate them with `pnpm api:generate`.",
      'export * from "./generated/index";',
      "",
    ].join("\n"),
    "utf8",
  );
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
