import { Injectable, BadRequestException, NotFoundException } from '@nestjs/common';
import { ProcessingJob, ExtractedDraft } from '@mo-nut/domain';
import * as crypto from 'crypto';

@Injectable()
export class OcrService {
  private jobs: Map<string, ProcessingJob> = new Map();
  private drafts: Map<string, ExtractedDraft> = new Map();

  /**
   * Create an async OCR processing job for a document
   */
  async createOcrJob(assetId: string, patientId: string): Promise<ProcessingJob> {
    const id = `job-${crypto.randomUUID().slice(0, 8)}`;
    const job: ProcessingJob = {
      id,
      schemaVersion: 1,
      version: 1,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      assetId,
      patientId,
      jobType: 'ocr',
      provider: 'mock_ocr_engine',
      status: 'uploaded',
      retryCount: 0,
    };

    this.jobs.set(id, job);

    // Auto-trigger async processing in next tick
    process.nextTick(async () => {
      try {
        await this.runOcrProcessing(id);
      } catch (err) {
        console.error(`Mock OCR processing failed for job ${id}:`, err);
      }
    });

    return job;
  }

  /**
   * Get OCR Job status
   */
  async getJob(id: string): Promise<ProcessingJob | null> {
    return this.jobs.get(id) || null;
  }

  /**
   * Get draft generated by the OCR job
   */
  async getDraftForJob(jobId: string): Promise<ExtractedDraft | null> {
    for (const draft of this.drafts.values()) {
      if (draft.jobId === jobId) return draft;
    }
    return null;
  }

  /**
   * Confirm/Approve a draft as human reviewed, transitioning the job
   */
  async confirmDraft(draftId: string, actorId: string): Promise<ExtractedDraft> {
    const draft = this.drafts.get(draftId);
    if (!draft) {
      throw new NotFoundException(`Draft ${draftId} not found`);
    }

    if (draft.reviewStatus !== 'pending') {
      throw new BadRequestException(`Draft already ${draft.reviewStatus}`);
    }

    draft.reviewStatus = 'approved';
    draft.reviewedBy = actorId;
    draft.reviewedAt = new Date().toISOString();
    draft.appliedAt = new Date().toISOString();
    draft.version += 1;
    draft.updatedAt = new Date().toISOString();
    this.drafts.set(draftId, draft);

    // Update job status to applied
    const job = this.jobs.get(draft.jobId);
    if (job) {
      job.status = 'applied';
      job.completedAt = new Date().toISOString();
      job.version += 1;
      job.updatedAt = new Date().toISOString();
      this.jobs.set(job.id, job);
    }

    return draft;
  }

  /**
   * Run Simulated async OCR processing
   */
  private async runOcrProcessing(jobId: string) {
    const job = this.jobs.get(jobId);
    if (!job) return;

    job.status = 'queued';
    this.jobs.set(jobId, job);

    await new Promise((resolve) => setTimeout(resolve, 100)); // Simulate async latency

    job.status = 'processing';
    this.jobs.set(jobId, job);

    await new Promise((resolve) => setTimeout(resolve, 100));

    // Simulate successful extraction
    job.status = 'review_required';
    job.completedAt = new Date().toISOString();
    job.version += 1;
    job.updatedAt = new Date().toISOString();
    this.jobs.set(jobId, job);

    // Create Draft object containing parsed results
    const draftId = `drf-${crypto.randomUUID().slice(0, 8)}`;
    const draft: ExtractedDraft = {
      id: draftId,
      schemaVersion: 1,
      version: 1,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      jobId,
      patientId: job.patientId,
      targetType: 'appointment',
      payload: {
        title: 'พบแพทย์อายุรกรรม (OCR)',
        facility: 'รพ.ศิริราช',
        address: 'กรุงเทพฯ',
        scheduledAt: '2026-06-30T10:00:00Z',
        timezone: 'Asia/Bangkok',
        preparations: [{ id: 'p1', description: 'งดน้ำและอาหาร 8 ชั่วโมง', isCompleted: false }],
      },
      confidence: 0.95,
      reviewStatus: 'pending',
    };

    this.drafts.set(draftId, draft);
  }
}
