import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const packageJson = JSON.parse(
  await readFile(new URL("../package.json", import.meta.url)),
);
assert.equal(packageJson.name, "@mo-nut/generated-client");

const indexText = await readFile(new URL("../src/index.ts", import.meta.url), "utf8");
assert.match(indexText, /Do not edit files under src\/generated by hand/);
