// This package exposes the generated OpenAPI client for web and mobile consumers.
// Do not edit files under src/generated by hand. Regenerate them with `pnpm api:generate`.
export * from "./generated/index";
